baseUrl = "/"
languageCode = "en-gb"
title = "Jon Cain ğŸ‘¨â€ğŸ’» (jonifen.co.uk)"
copyright = "(c) 2022 Jon Cain"
Paginate = 8

[taxonomies]
  tag = "tags"

[params]
  indexSections = ["blog"]
  indexPostCount = 5
  footline = "[jonifen.co.uk](https://jonifen.co.uk) - Created using [Hugo](https://gohugo.io)"
  description = "This is a blog about software development, general tech stuff and some completely random junk!"
  images = ["images/og-avatar.png"]
  summary = "This is a blog about software development, general tech stuff and some completely random junk!"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 2