baseUrl = "/"
languageCode = "en-gb"
title = "Jonifen ğŸ‘¨â€ğŸ’»"
copyright = "(c) 2020 Jon Cain"

[taxonomies]
	tag = "tags"

[params]
	footline = "[jonifen.co.uk](https://jonifen.co.uk) - Created using [Hugo](https://gohugo.io)"
